In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB



/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.5
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:
df = pd.read_csv("/kaggle/input/titanicpassengersurvivalrate/titanicpassengersurvivalrate.csv")

In [3]:
df

PassengerId  Pclass  Male  Female   Age  Survived
0              1       3     1       0  22.0         0
1              2       1     0       1  38.0         1
2              3       3     0       1  26.0         1
3              4       1     0       1  35.0         1
4              5       3     1       0  35.0         0
..           ...     ...   ...     ...   ...       ...
886          887       2     1       0  27.0         0
887          888       1     0       1  19.0         1
888          889       3     0       1   3.0         0
889          890       1     1       0  26.0         1
890          891       3     1       0  32.0         0

[891 rows x 6 columns]

In [4]:
df.count

<bound method DataFrame.count of      PassengerId  Pclass  Male  Female   Age  Survived
0              1       3     1       0  22.0         0
1              2       1     0       1  38.0         1
2              3       3     0       1  26.0         1
3              4       1     0       1  35.0         1
4              5       3     1       0  35.0         0
..           ...     ...   ...     ...   ...       ...
886          887       2     1       0  27.0         0
887          888       1     0       1  19.0         1
888          889       3     0       1   3.0         0
889          890       1     1       0  26.0         1
890          891       3     1       0  32.0         0

[891 rows x 6 columns]>

In [5]:
df.isna().sum()

PassengerId    0
Pclass         0
Male           0
Female         0
Age            0
Survived       0
dtype: int64

In [6]:
df.describe()

PassengerId      Pclass        Male      Female         Age    Survived
count   891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean    446.000000    2.308642    0.647587    0.352413   29.718485    0.383838
std     257.353842    0.836071    0.477990    0.477990   14.026406    0.486592
min       1.000000    1.000000    0.000000    0.000000    0.420000    0.000000
25%     223.500000    2.000000    0.000000    0.000000   21.000000    0.000000
50%     446.000000    3.000000    1.000000    0.000000   28.000000    0.000000
75%     668.500000    3.000000    1.000000    1.000000   36.000000    1.000000
max     891.000000    3.000000    1.000000    1.000000   88.000000    1.000000

In [7]:
x = df.drop(['Survived'], axis = 1)
y = df[['Survived']]

In [8]:
trainX, testX, trainY, testY = train_test_split(x, y, test_size = 0.2 )

# **Decision Tree**

In [9]:
dtc = DecisionTreeClassifier()
dtc.fit(trainX, trainY)

DecisionTreeClassifier()

In [10]:
y_predicted = dtc.predict(testX)

In [11]:
confusion_matrix (testY, y_predicted)

array([[94, 23],
       [25, 37]])

In [12]:
tp = 92
fn = 4
fp = 0
tn = 109
precision = tp/(tp + fp)
recall = tp/(tp + fn)
specificity = tn/(fp + tn)
f1 = 2 * (precision * recall) / (precision + recall)
precision, recall, specificity, f1

(1.0, 0.9583333333333334, 1.0, 0.9787234042553191)

# **SVM**

In [13]:
svm = SVC(kernel = 'linear')
svm.fit (trainX, trainY.values.ravel())

SVC(kernel='linear')

In [14]:
y_predicted = svm.predict (testX)

In [15]:
confusion_matrix (testY, y_predicted)

array([[97, 20],
       [20, 42]])

In [16]:
tp = 67
fn = 27
fp = 9
tn = 100
precision = tp/(tp + fp)
recall = tp/(tp + fn)
specificity = tn/(fp + tn)
f1 = 2 * ( precision*recall)/(precision+recall)
precision, recall, specificity, f1

(0.881578947368421, 0.7127659574468085, 0.9174311926605505, 0.788235294117647)

# **Naive Bayes**

In [17]:
nb = GaussianNB ()
nb.fit (trainX, trainY.values.ravel())

GaussianNB()

In [18]:
y_predicted = nb.predict (testX)

In [19]:
confusion_matrix (testY, y_predicted)

array([[97, 20],
       [20, 42]])

In [20]:
tp = 73
fn = 23
fp = 12
tn = 97
precision = tp/(tp + fp)
recall = tp/(tp + fn)
specificity = tn/(fp + tn)
f1 = 2 * ( precision*recall)/(precision+recall)
precision, recall, specificity, f1

(0.8588235294117647,
 0.7604166666666666,
 0.8899082568807339,
 0.8066298342541436)

# **Random Forest**

In [21]:
rf = RandomForestClassifier ()
rf.fit (trainX, trainY.values.ravel())

RandomForestClassifier()

In [22]:
y_predicted = svm.predict (testX)
y_actual = testY

In [23]:
confusion_matrix (testY, y_predicted)

array([[97, 20],
       [20, 42]])

In [24]:
tp = 69
fn = 27
fp = 9
tn = 100
precision = tp/(tp + fp)
recall = tp/(tp + fn)
specificity = tn/(fp + tn)
f1 = 2 * ( precision*recall)/(precision+recall)
precision, recall, specificity, f1

(0.8846153846153846, 0.71875, 0.9174311926605505, 0.7931034482758621)